import { CandidateProfile, TargetJob, InterviewQuestion, CopilotKnowledgeItem } from "./types";

export const CANDIDATE_PROFILES: CandidateProfile[] = [
  {
    id: "alex-chen",
    name: "Alex Chen",
    avatarInitials: "AC",
    currentTitle: "Senior Frontend Engineer",
    targetRole: "Staff Frontend Architect",
    experienceLevel: "Staff / Principal",
    baseResumeScore: 94,
    baseAtsScore: 91,
    baseKeywordMatch: 88,
    atsParsedKeywords: 38,
    subScores: {
      quantifiedImpact: 96,
      actionVerbs: 93,
      atsParseIntegrity: 98,
      keywordDensity: 89,
    },
    strengths: [
      "React 19 Server Components",
      "Next.js 15 Streaming SSR",
      "Sub-0.8s LCP Budgeting",
      "Design Systems Architecture",
      "TypeScript Strict Concurrency",
    ],
    missingSkills: ["CRDT Offline Sync", "OpenTelemetry Tracing", "WebAssembly (WASM) Modules"],
    skillRadar: [
      { name: "System Design", current: 92, target: 96 },
      { name: "React / Next.js", current: 98, target: 95 },
      { name: "Core Web Vitals", current: 95, target: 98 },
      { name: "Algorithms", current: 82, target: 90 },
      { name: "STAR Leadership", current: 90, target: 94 },
      { name: "Edge & Telemetry", current: 78, target: 92 },
    ],
    suggestions: [
      {
        id: "ac-sug-1",
        field: "Architecture Impact",
        type: "replacement",
        before: "Built micro-frontend components and optimized page loading times for customer checkout.",
        after: "Architected Next.js 15 streaming SSR checkout pipeline, reducing LCP by 420ms (-34%) and cutting bundle size by 180kB across 2.4M monthly active sessions.",
        impactScore: "+18",
        impactDescription: "Demonstrates quantified Staff-level latency metrics and revenue-critical scope.",
      },
      {
        id: "ac-sug-2",
        field: "Distributed State",
        type: "addition",
        before: "Maintained global Redux state across multiple client modules.",
        after: "Engineered optimistic state reconciliation layer with zero-latency rollback, decreasing state sync error rates from 4.2% to 0.08%.",
        impactScore: "+12",
        impactDescription: "Demonstrates deep concurrency management and fault-tolerance ownership.",
      },
      {
        id: "ac-sug-3",
        field: "Engineering Leadership",
        type: "replacement",
        before: "Helped junior developers with code reviews and documentation.",
        after: "Authored 8 core RFCs, mentored 6 engineers (2 promoted to Senior), and standardized company-wide TypeScript strictness rules across 40+ repositories.",
        impactScore: "+15",
        impactDescription: "Shows org-wide multiplication factor and structured mentorship impact.",
      },
    ],
    roadmapMilestones: [
      {
        id: 1,
        phase: "Week 1 - 2",
        title: "React 19 Compiler & Streaming Hydration Internals",
        status: "completed",
        description: "Master React Server Component wire formats, streaming HTML boundaries, and hydration mismatch prevention.",
        deliverable: "Benchmark 5 SSR rendering modes under 500ms 3G network throttling.",
        skills: ["React 19", "Streaming SSR", "Bundle Budgeting"],
        estimatedHours: 18,
      },
      {
        id: 2,
        phase: "Week 3 - 4",
        title: "Distributed State Machines & CRDT Sync",
        status: "completed",
        description: "Design fault-tolerant offline-first client architecture using Yjs, WebSockets, and IndexedDB backup queues.",
        deliverable: "Collaborative rich-text editor with automatic edge conflict resolution.",
        skills: ["CRDTs", "WebSockets", "XState"],
        estimatedHours: 24,
      },
      {
        id: 3,
        phase: "Week 5 - 6",
        title: "Edge Telemetry & OpenTelemetry Tracing",
        status: "in-progress",
        description: "Instrument client-to-edge distributed tracing, Core Web Vitals RUM metrics, and error boundary alarms.",
        deliverable: "Grafana dashboard tracking LCP, FID/INP, and CLS across edge nodes.",
        skills: ["OpenTelemetry", "RUM", "Edge Workers"],
        estimatedHours: 20,
      },
      {
        id: 4,
        phase: "Week 7 - 8",
        title: "Executive RFC Negotiation & Staff Behavioral",
        status: "upcoming",
        description: "Simulate 8 high-stakes executive interview rounds defending multi-million dollar tech stack transitions.",
        deliverable: "Published technical whitepaper and STAR portfolio answers.",
        skills: ["STAR Framework", "Cross-Org RFCs", "System Design"],
        estimatedHours: 16,
      },
    ],
  },
  {
    id: "sarah-jenkins",
    name: "Sarah Jenkins",
    avatarInitials: "SJ",
    currentTitle: "Senior Fullstack Developer",
    targetRole: "Senior Platform Engineer",
    experienceLevel: "Senior",
    baseResumeScore: 85,
    baseAtsScore: 83,
    baseKeywordMatch: 79,
    atsParsedKeywords: 29,
    subScores: {
      quantifiedImpact: 84,
      actionVerbs: 86,
      atsParseIntegrity: 92,
      keywordDensity: 80,
    },
    strengths: [
      "Node.js Microservices",
      "PostgreSQL Optimization",
      "TypeScript & REST APIs",
      "Tailwind CSS & Next.js",
      "Dockerized Deployments",
    ],
    missingSkills: ["GraphQL Federation", "Distributed Tracing", "Kubernetes Pod Autoscaling"],
    skillRadar: [
      { name: "System Design", current: 80, target: 92 },
      { name: "React / Next.js", current: 88, target: 90 },
      { name: "Core Web Vitals", current: 75, target: 88 },
      { name: "Algorithms", current: 85, target: 88 },
      { name: "STAR Leadership", current: 78, target: 88 },
      { name: "Edge & Telemetry", current: 65, target: 85 },
    ],
    suggestions: [
      {
        id: "sj-sug-1",
        field: "Database Performance",
        type: "replacement",
        before: "Improved database queries and fixed slow loading endpoints.",
        after: "Optimized PostgreSQL indexes and partitioned high-traffic transaction tables, reducing p99 API query latency from 850ms to 42ms for 500k daily records.",
        impactScore: "+16",
        impactDescription: "Translates routine DB fixes into enterprise-grade p99 latency gains.",
      },
      {
        id: "sj-sug-2",
        field: "API Architecture",
        type: "addition",
        before: "Created REST API endpoints in Express and Node.",
        after: "Built resilient API Gateway with rate limiting and automated Swagger schema validation, handling 18k RPM with 99.99% uptime SLA.",
        impactScore: "+14",
        impactDescription: "Adds reliability and SLA measurements expected for platform roles.",
      },
    ],
    roadmapMilestones: [
      {
        id: 1,
        phase: "Week 1 - 2",
        title: "Distributed Caching & Redis Cluster Sharding",
        status: "completed",
        description: "Implement multi-tier cache invalidation strategies and cache-stampede mitigation.",
        deliverable: "Redis cache layer with sub-5ms lookup and stale-while-revalidate fallbacks.",
        skills: ["Redis", "Caching", "Node.js Streams"],
        estimatedHours: 20,
      },
      {
        id: 2,
        phase: "Week 3 - 4",
        title: "Kubernetes & Multi-Zone Container Orchestration",
        status: "in-progress",
        description: "Author Helm charts, HPA autoscaling policies, and blue-green canary deployments.",
        deliverable: "Automated zero-downtime canary deployment pipeline.",
        skills: ["Kubernetes", "Docker", "CI/CD"],
        estimatedHours: 25,
      },
      {
        id: 3,
        phase: "Week 5 - 6",
        title: "GraphQL Federation & Subgraph Gateways",
        status: "upcoming",
        description: "Federate 4 monolithic services into unified GraphQL schema with Apollo Router.",
        deliverable: "Federated gateway with batch dataloading and query depth limiting.",
        skills: ["GraphQL", "Apollo", "Schema Design"],
        estimatedHours: 22,
      },
    ],
  },
  {
    id: "marcus-vance",
    name: "Marcus Vance",
    avatarInitials: "MV",
    currentTitle: "Senior Backend Engineer",
    targetRole: "Distributed Systems Tech Lead",
    experienceLevel: "Staff / Principal",
    baseResumeScore: 92,
    baseAtsScore: 89,
    baseKeywordMatch: 86,
    atsParsedKeywords: 35,
    subScores: {
      quantifiedImpact: 94,
      actionVerbs: 91,
      atsParseIntegrity: 96,
      keywordDensity: 88,
    },
    strengths: [
      "Go & Rust Concurrency",
      "Kafka Event Streaming",
      "gRPC & Protobuf",
      "PostgreSQL Partitions",
      "Distributed Rate Limiting",
    ],
    missingSkills: ["eBPF Kernel Probing", "Raft Consensus Protocol", "Envoy Service Mesh"],
    skillRadar: [
      { name: "System Design", current: 95, target: 98 },
      { name: "React / Next.js", current: 60, target: 70 },
      { name: "Core Web Vitals", current: 55, target: 65 },
      { name: "Algorithms", current: 94, target: 96 },
      { name: "STAR Leadership", current: 88, target: 92 },
      { name: "Edge & Telemetry", current: 92, target: 96 },
    ],
    suggestions: [
      {
        id: "mv-sug-1",
        field: "High-Throughput Streaming",
        type: "replacement",
        before: "Wrote backend services to process queue messages in Kafka.",
        after: "Architected distributed Kafka pipeline processing 45k events/sec with zero message loss and exactly-once semantics across 12 worker clusters.",
        impactScore: "+20",
        impactDescription: "Highlights enterprise event throughput and data consistency guarantees.",
      },
    ],
    roadmapMilestones: [
      {
        id: 1,
        phase: "Week 1 - 3",
        title: "Raft Consensus Algorithm from Scratch in Go",
        status: "in-progress",
        description: "Implement leader election, log replication, and heartbeat fault-tolerance.",
        deliverable: "3-node distributed Key-Value store passing Jepsen partition tests.",
        skills: ["Go", "Raft", "Distributed Consensus"],
        estimatedHours: 35,
      },
      {
        id: 2,
        phase: "Week 4 - 6",
        title: "eBPF Network Observability & Kernel Tracing",
        status: "upcoming",
        description: "Write kernel-level probe programs to trace TCP socket lifecycle and packet drops.",
        deliverable: "Real-time socket latency monitoring daemon.",
        skills: ["eBPF", "C", "Linux Kernel"],
        estimatedHours: 28,
      },
    ],
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    avatarInitials: "PS",
    currentTitle: "Machine Learning Engineer",
    targetRole: "GenAI Infrastructure Engineer",
    experienceLevel: "Senior",
    baseResumeScore: 88,
    baseAtsScore: 86,
    baseKeywordMatch: 84,
    atsParsedKeywords: 32,
    subScores: {
      quantifiedImpact: 89,
      actionVerbs: 88,
      atsParseIntegrity: 94,
      keywordDensity: 83,
    },
    strengths: [
      "PyTorch & Transformers",
      "CUDA Kernel Optimization",
      "Vector DBs (Qdrant, Pinecone)",
      "LangChain & LlamaIndex",
      "Python Microservices",
    ],
    missingSkills: ["Triton Inference Server", "TensorRT-LLM", "FlashAttention Kernels"],
    skillRadar: [
      { name: "System Design", current: 86, target: 94 },
      { name: "React / Next.js", current: 65, target: 75 },
      { name: "Core Web Vitals", current: 50, target: 65 },
      { name: "Algorithms", current: 92, target: 95 },
      { name: "STAR Leadership", current: 82, target: 90 },
      { name: "Edge & Telemetry", current: 85, target: 92 },
    ],
    suggestions: [
      {
        id: "ps-sug-1",
        field: "Model Serving Latency",
        type: "replacement",
        before: "Deployed language models on cloud servers for chat search.",
        after: "Engineered high-throughput LLM inference pipeline with dynamic batching and vLLM quantization (AWQ), slashing TTFT from 820ms to 110ms while cutting GPU compute cost by 48%.",
        impactScore: "+22",
        impactDescription: "Crucial metric for AI infrastructure roles (TTFT, quantization, cost efficiency).",
      },
    ],
    roadmapMilestones: [
      {
        id: 1,
        phase: "Week 1 - 2",
        title: "TensorRT-LLM Engine Compilation & PagedAttention",
        status: "in-progress",
        description: "Benchmark KV cache memory management and FP8 quantization kernels.",
        deliverable: "Serving Llama-3-70B at 90 tokens/sec on 2x A100 GPUs.",
        skills: ["TensorRT", "CUDA", "LLM Inference"],
        estimatedHours: 25,
      },
    ],
  },
  {
    id: "elena-rostova",
    name: "Elena Rostova",
    avatarInitials: "ER",
    currentTitle: "Staff Software Engineer / Team Lead",
    targetRole: "Engineering Manager / Director of Eng",
    experienceLevel: "Engineering Leader",
    baseResumeScore: 96,
    baseAtsScore: 94,
    baseKeywordMatch: 92,
    atsParsedKeywords: 44,
    subScores: {
      quantifiedImpact: 98,
      actionVerbs: 95,
      atsParseIntegrity: 99,
      keywordDensity: 94,
    },
    strengths: [
      "Cross-Org Engineering RFCs",
      "Executive Hiring & Retention",
      "Engineering Capacity Planning",
      "Multi-Quarter Roadmapping",
      "Vendor & Cloud Budget Auditing",
    ],
    missingSkills: ["Multi-Org Headcount Financial Modeling", "M&A Technical Due Diligence"],
    skillRadar: [
      { name: "System Design", current: 94, target: 96 },
      { name: "React / Next.js", current: 75, target: 80 },
      { name: "Core Web Vitals", current: 80, target: 85 },
      { name: "Algorithms", current: 85, target: 88 },
      { name: "STAR Leadership", current: 98, target: 98 },
      { name: "Edge & Telemetry", current: 86, target: 90 },
    ],
    suggestions: [
      {
        id: "er-sug-1",
        field: "Org Scalability",
        type: "replacement",
        before: "Managed a team of 10 developers and planned quarterly sprints.",
        after: "Directed 22-engineer distributed organization across 3 squads; increased sprint throughput by 38%, cut critical production incidents by 64%, and achieved 0% voluntary turnover in 24 months.",
        impactScore: "+25",
        impactDescription: "Shows exceptional organizational leadership, retention metrics, and velocity multiplier.",
      },
    ],
    roadmapMilestones: [
      {
        id: 1,
        phase: "Week 1 - 2",
        title: "Executive Incident Post-Mortem & SLA Governance",
        status: "completed",
        description: "Author comprehensive executive review documents analyzing 99.999% availability standards.",
        deliverable: "Standardized SLA error budget playbook adopted by 5 business units.",
        skills: ["SRE Governance", "Executive Writing", "Risk Mitigation"],
        estimatedHours: 15,
      },
    ],
  },
];

export const TARGET_JOBS: TargetJob[] = [
  {
    id: "job-stripe",
    title: "Staff Frontend Architect",
    company: "Stripe",
    location: "San Francisco, CA / Remote",
    salaryBand: "$240k - $320k + Equity",
    matchScore: 94,
    requiredKeywords: ["React 19", "Next.js", "TypeScript", "Core Web Vitals", "Design Systems", "Streaming SSR"],
    bonusKeywords: ["CRDTs", "WASM", "OpenTelemetry", "XState"],
    description: "Architect the next generation of mission-critical merchant checkout surfaces handling billions in global transactions with zero downtime and sub-second rendering.",
  },
  {
    id: "job-vercel",
    title: "Senior Platform & Edge Engineer",
    company: "Vercel",
    location: "San Francisco, CA / Remote",
    salaryBand: "$190k - $260k + Equity",
    matchScore: 89,
    requiredKeywords: ["Edge Workers", "Node.js", "TypeScript", "Redis", "Distributed Caching", "Server Actions"],
    bonusKeywords: ["Kubernetes", "GraphQL", "eBPF", "Grafana"],
    description: "Build ultra-low latency compute infrastructure and developer tooling enabling millions of frontend developers worldwide to deploy instantly.",
  },
  {
    id: "job-aws",
    title: "Distributed Systems Tech Lead",
    company: "AWS Core Infrastructure",
    location: "Seattle, WA / Remote",
    salaryBand: "$220k - $310k + Equity",
    matchScore: 91,
    requiredKeywords: ["Go", "Rust", "Kafka", "Distributed Consensus", "gRPC", "High Concurrency"],
    bonusKeywords: ["Raft", "eBPF", "Envoy", "Linux Kernel"],
    description: "Design multi-region partition-tolerant storage and messaging layers powering global cloud workloads at massive scale.",
  },
  {
    id: "job-openai",
    title: "GenAI Infrastructure Engineer",
    company: "OpenAI",
    location: "San Francisco, CA",
    salaryBand: "$250k - $360k + Equity",
    matchScore: 88,
    requiredKeywords: ["PyTorch", "CUDA", "TensorRT", "Model Quantization", "Vector DBs", "LLM Inference"],
    bonusKeywords: ["vLLM", "FlashAttention", "Triton Server", "Triton"],
    description: "Optimize high-throughput neural network inference engines, reduce token time-to-first-byte, and scale GPU cluster orchestration.",
  },
];

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // Frontend Architecture (10 questions)
  {
    id: "fe-1",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Staff Level",
    title: "Hydration Mismatches & Streaming SSR",
    question: "Walk me through how you benchmark and eliminate client/server hydration mismatches in a large-scale React 19 streaming SSR application.",
    hints: [
      "Mention selective hydration with Suspense boundaries",
      "Explain the wire format of React Server Components",
      "Discuss how to isolate browser-only APIs (localStorage, window) safely",
    ],
    evaluationRubric: {
      situation: "Explains high-traffic checkout page with intermittent layout shifts.",
      task: "Assigned to eliminate runtime reconciliation errors without disabling SSR.",
      action: "Isolated dynamic client state into deferred Suspense islands with explicit placeholder aspect ratios.",
      result: "Zero hydration errors across 12M sessions; reduced LCP from 2.1s to 780ms.",
    },
    candidateSnippet: "We enforced strict SSR component boundaries, streamed critical path HTML above the fold, and isolated client hydration using React 19 Server Components with explicit image aspect ratio placeholders...",
    starBreakdown: { situation: 94, task: 96, action: 97, result: 95 },
    pacing: "144 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 96,
  },
  {
    id: "fe-2",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Hard",
    title: "Micro-Frontend State Isolation",
    question: "How do you coordinate shared state between 8 independent micro-frontends without tight coupling or bundle bloat?",
    hints: ["Custom DOM events with typed payloads", "Shared event bus via BroadcastChannel", "Single-SPA or Module Federation isolation"],
    evaluationRubric: {
      situation: "Multi-team monolith breaking into independent deployment units.",
      task: "Establish decoupled state bridge for user session and cart count.",
      action: "Built typed CustomEvent pub/sub bus with strict JSON schema validation and zero npm dependencies.",
      result: "Independent deployments achieved with sub-5ms event dispatch overhead.",
    },
    candidateSnippet: "Rather than sharing a heavyweight global store across runtime boundaries, we introduced an immutable CustomEvent communication layer with TypeScript contracts...",
    starBreakdown: { situation: 92, task: 94, action: 95, result: 91 },
    pacing: "139 WPM (Confident)",
    fillerWords: "1 detected ('like')",
    score: 93,
  },
  {
    id: "fe-3",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Hard",
    title: "Optimistic UI Rollbacks & Conflict Resolution",
    question: "Describe your implementation of an optimistic UI mutation strategy that gracefully handles network failures without flashing layout shifts.",
    hints: ["Snapshot previous state in cache before dispatch", "Apply optimistic update immediately to UI", "Rollback on error with localized retry toast"],
    evaluationRubric: {
      situation: "User updates complex kanban board offline on mobile.",
      task: "Keep UI feeling instant (0ms latency) while ensuring data consistency.",
      action: "Utilized TanStack Query optimistic mutation hooks with rollback snapshots in IndexedDB.",
      result: "Zero perceived input latency and 100% state recovery on intermittent 3G.",
    },
    candidateSnippet: "When a user drags a task card, we immediately apply the new coordinate in the localized cache snapshot, dispatch the mutation with an idempotency key, and rollback with micro-animations if the server returns 4xx...",
    starBreakdown: { situation: 95, task: 93, action: 98, result: 94 },
    pacing: "142 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 95,
  },
  {
    id: "fe-4",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Medium",
    title: "Core Web Vitals INP (Interaction to Next Paint)",
    question: "How do you diagnose and fix a 350ms INP bottleneck on a dense data grid with 10,000 rows?",
    hints: ["Virtualization (react-window / TanStack Virtual)", "Web Worker sorting and filtering", "useTransition to avoid blocking main thread"],
    evaluationRubric: {
      situation: "Data table frozen for 350ms when typing search filter.",
      task: "Bring INP below the 100ms Google threshold.",
      action: "Implemented windowed virtualization and moved regex search execution into a Dedicated Web Worker.",
      result: "Reduced INP from 350ms to 28ms; zero frame drops during active typing.",
    },
    candidateSnippet: "Using Chrome Performance profiler, I traced the long task to synchronous DOM reconciliation. I wrapped the filter state in startTransition and offloaded fuzzy matching to a Web Worker...",
    starBreakdown: { situation: 90, task: 95, action: 96, result: 93 },
    pacing: "145 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 94,
  },
  {
    id: "fe-5",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Staff Level",
    title: "Design System Token Synchronization",
    question: "How do you architect a multi-brand design system that syncs design tokens from Figma to React, iOS, and Android automatically?",
    hints: ["Style Dictionary for token transformation", "GitHub Actions CI pipeline on Figma webhook", "CSS custom properties with fallback maps"],
    evaluationRubric: {
      situation: "Design inconsistency across Web, iOS, and Android platforms.",
      task: "Automate token pipeline to eliminate manual handoffs.",
      action: "Created Style Dictionary build pipeline triggered via Figma REST API webhooks.",
      result: "Token deployment time cut from 2 weeks to 4 minutes.",
    },
    candidateSnippet: "We established a single source of truth in Figma using semantic token variables, which dispatched webhooks to a GitHub Action running Style Dictionary...",
    starBreakdown: { situation: 94, task: 96, action: 95, result: 96 },
    pacing: "140 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 95,
  },
  {
    id: "fe-6",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Hard",
    title: "Memory Leak Detection in Single Page Apps",
    question: "How do you detect, isolate, and eliminate memory leaks caused by uncleaned event listeners and detached DOM nodes?",
    hints: ["Chrome Memory Tab Heap Snapshots", "WeakRef and FinalizationRegistry", "Retainer tree inspection"],
    evaluationRubric: {
      situation: "SPA tab crashing after 2 hours of active usage.",
      task: "Find root cause of steady 2MB/min heap growth.",
      action: "Took 3 sequential heap snapshots and compared constructor retaining paths.",
      result: "Identified uncleaned ResizeObserver; freed 450MB of retained memory.",
    },
    candidateSnippet: "I recorded heap allocation timelines in Chrome DevTools, isolated detached HTMLDivElements retained by a singleton event dispatcher, and implemented WeakMap references...",
    starBreakdown: { situation: 93, task: 92, action: 97, result: 94 },
    pacing: "138 WPM (Confident)",
    fillerWords: "0 detected",
    score: 94,
  },
  {
    id: "fe-7",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Medium",
    title: "Asset Loading Strategy & Critical CSS",
    question: "Explain your methodology for inlining critical CSS while asynchronously prefetching next-route JavaScript bundles.",
    hints: ["Next.js automatic critical CSS extraction", "link rel='modulepreload'", "IntersectionObserver route prefetching"],
    evaluationRubric: {
      situation: "Mobile users experiencing 1.8s render-blocking CSS delay.",
      task: "Inline above-the-fold critical CSS and prefetch chunks on viewport entry.",
      action: "Configured Critters CSS parser and speculative link prefetching.",
      result: "First Contentful Paint improved by 650ms.",
    },
    candidateSnippet: "We inlined the critical 14kB of CSS required for above-the-fold rendering directly in the initial document stream, while registering a service worker to cache subsequent route chunks...",
    starBreakdown: { situation: 90, task: 92, action: 94, result: 92 },
    pacing: "141 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 92,
  },
  {
    id: "fe-8",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Staff Level",
    title: "WebAssembly in the Browser for Heavy Compute",
    question: "When would you choose WebAssembly over Web Workers for frontend computation, and how do you bridge memory between JS and Rust WASM?",
    hints: ["SharedArrayBuffer memory transfer", "wasm-bindgen serialization overhead", "Compute-heavy image/audio manipulation"],
    evaluationRubric: {
      situation: "Client-side PDF parsing and signature verification lagging UI.",
      task: "Speed up cryptographic parsing by at least 5x.",
      action: "Compiled Rust crypto engine to WASM using wasm-pack with SharedArrayBuffer zero-copy buffers.",
      result: "Parsing time dropped from 1.4s to 85ms.",
    },
    candidateSnippet: "We compiled our cryptographic verification module in Rust to WASM, minimizing serialization boundaries by passing raw memory pointers via TypedArrays directly into WASM linear memory...",
    starBreakdown: { situation: 96, task: 95, action: 98, result: 97 },
    pacing: "143 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 97,
  },
  {
    id: "fe-9",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Hard",
    title: "Accessibility (a11y) Architecture for Complex Modals",
    question: "How do you build an accessible polymorphic modal system with focus trapping, ARIA roles, and screen reader announcements?",
    hints: ["Focus trapping with first/last tabbable elements", "role='dialog' and aria-modal='true'", "aria-live announcement for async status changes"],
    evaluationRubric: {
      situation: "Audit flagged critical WCAG AA keyboard focus traps.",
      task: "Re-architect modal primitive to be 100% accessible.",
      action: "Implemented inert polyfill, focus restoration on unmount, and keyboard Escape listeners.",
      result: "Achieved perfect 100% Lighthouse Accessibility score.",
    },
    candidateSnippet: "We trapped Tab/Shift+Tab focus cycles inside the modal container, restored document.activeElement on unmount, and set inert attributes on background landmarks...",
    starBreakdown: { situation: 94, task: 95, action: 96, result: 95 },
    pacing: "140 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 95,
  },
  {
    id: "fe-10",
    category: "frontend",
    categoryLabel: "Frontend Architecture",
    difficulty: "Medium",
    title: "Strict TypeScript Polymorphism in UI Libraries",
    question: "How do you build a polymorphic UI `Button` component in TypeScript that safely inherits HTML element props based on the `as` prop?",
    hints: ["ComponentPropsWithRef<C>", "React.ElementType generic", "forwardRef with explicit generic wrapper"],
    evaluationRubric: {
      situation: "UI button component failing TypeScript checks when rendered as an anchor link.",
      task: "Create generic polymorphic ComponentPropsWithRef typings.",
      action: "Wrote generic polymorphic wrapper supporting href, type, and custom React router Link components.",
      result: "Full type safety and autocomplete across 150+ component consumers.",
    },
    candidateSnippet: "We used a generic type parameter extending ElementType with ComponentPropsWithRef, allowing the button to safely render as button, anchor, or custom Link with full TypeScript inference...",
    starBreakdown: { situation: 92, task: 94, action: 95, result: 93 },
    pacing: "142 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 94,
  },

  // System Design (10 questions)
  {
    id: "sd-1",
    category: "system_design",
    categoryLabel: "System Design",
    difficulty: "Staff Level",
    title: "Real-Time Collaborative Document Editor",
    question: "How would you design a real-time collaborative document editor like Google Docs with offline-first CRDT support and edge conflict resolution?",
    hints: ["Yjs / Automerge CRDT data structures", "WebSockets with fallback to SSE / Long Polling", "IndexedDB client persistence queue"],
    evaluationRubric: {
      situation: "Building multi-user real-time document editor with network instability.",
      task: "Prevent document state divergence and data loss during concurrent edits.",
      action: "Adopted Yjs State Vectors synced over WebSockets with optimistic IndexedDB transaction logs.",
      result: "Zero data divergence across 50 simultaneous editors per room; sub-40ms sync latency.",
    },
    candidateSnippet: "I started by establishing a vector clock hierarchy at the client edge layer. For concurrency, we adopted Yjs CRDTs synced over WebSockets with an optimistic UI fallback. During network partitions, transactions are queued in IndexedDB...",
    starBreakdown: { situation: 95, task: 92, action: 96, result: 90 },
    pacing: "142 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 94,
  },
  {
    id: "sd-2",
    category: "system_design",
    categoryLabel: "System Design",
    difficulty: "Hard",
    title: "Distributed Rate Limiter at Edge",
    question: "Design a multi-region distributed rate limiter handling 200k RPS with sliding window counter algorithms and Redis cluster failover.",
    hints: ["Sliding window log vs Sliding window counter", "Redis Lua script execution for atomicity", "Local memory in-process cache with leaky bucket"],
    evaluationRubric: {
      situation: "DDoS spikes threatening upstream authentication services.",
      task: "Enforce strict per-API-key rate limits under 2ms latency.",
      action: "Implemented Redis atomic Lua sliding window script with local in-memory Bloom filter bypass.",
      result: "Blocked 99.8% of malicious bursts with <1.2ms added request overhead.",
    },
    candidateSnippet: "We implemented an edge-level sliding window counter using Redis Lua scripts to ensure atomic increments and TTL expirations in a single round-trip...",
    starBreakdown: { situation: 94, task: 96, action: 97, result: 95 },
    pacing: "143 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 96,
  },
  {
    id: "sd-3",
    category: "system_design",
    categoryLabel: "System Design",
    difficulty: "Staff Level",
    title: "Global Notification Delivery System",
    question: "Design a notification system delivering 50 million push, email, and SMS notifications daily with priority queues and deduplication.",
    hints: ["Kafka topic partitioning by priority", "Redis idempotent key check for 24h deduplication", "Third-party vendor fallback routing (Twilio / SendGrid / FCM)"],
    evaluationRubric: {
      situation: "Transactional notification delays causing user drop-off.",
      task: "Guarantee p99 delivery under 5 seconds with zero duplicate sends.",
      action: "Created prioritized Kafka queues and distributed deduplication cache.",
      result: "Delivered 50M messages daily with 99.98% delivery rate within 3 seconds.",
    },
    candidateSnippet: "We decoupled ingestion from dispatch using high-throughput Kafka topics partitioned by urgency tier, utilizing Redis idempotency keys to guarantee exactly-once delivery...",
    starBreakdown: { situation: 93, task: 95, action: 96, result: 94 },
    pacing: "140 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 95,
  },

  // Behavioral & Leadership (10 questions)
  {
    id: "beh-1",
    category: "behavioral",
    categoryLabel: "Behavioral (STAR)",
    difficulty: "Staff Level",
    title: "Architectural Disagreement & RFC Consensus",
    question: "Tell me about a time when your engineering team fundamentally disagreed on an architectural choice for a high-priority launch.",
    hints: ["State the opposing viewpoints objectively", "Explain how you established objective evaluation benchmarks", "Demonstrate consensus-building and ownership"],
    evaluationRubric: {
      situation: "Engineering team deadlocked between GraphQL and REST with tRPC.",
      task: "Lead decision-making process to avoid delaying Q3 product launch.",
      action: "Authored comparative RFC prototype matrix scoring bundle size, caching, and type safety.",
      result: "Team reached unanimous consensus in 1 week; shipped 2 weeks ahead of target.",
    },
    candidateSnippet: "Our team was split between GraphQL federation and REST with tRPC. As tech lead, I authored an objective RFC matrix testing bundle cost, type safety, and cache invalidation across 3 prototype endpoints...",
    starBreakdown: { situation: 92, task: 94, action: 98, result: 93 },
    pacing: "138 WPM (Confident)",
    fillerWords: "1 detected ('like')",
    score: 95,
  },
  {
    id: "beh-2",
    category: "behavioral",
    categoryLabel: "Behavioral (STAR)",
    difficulty: "Hard",
    title: "High-Severity Production Outage Response",
    question: "Describe how you managed a high-severity production outage affecting revenue, and how you led the post-mortem analysis.",
    hints: ["Immediate stabilization over root-cause debate", "Clear executive stakeholder communication", "Blameless post-mortem with preventative actions"],
    evaluationRubric: {
      situation: "Payment gateway timeout causing 25% checkout error rate.",
      task: "Restore transaction processing within 15 minutes SLA.",
      action: "Activated circuit breaker to secondary gateway and coordinated cross-functional war room.",
      result: "Full service restored in 9 minutes; 0 data lost; instituted automated failover integration tests.",
    },
    candidateSnippet: "When automated alarms triggered on a 25% payment failure spike, I immediately assumed incident commander, enabled our secondary payment fallback circuit breaker, and sent 15-minute status updates to executives...",
    starBreakdown: { situation: 96, task: 95, action: 98, result: 96 },
    pacing: "142 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 96,
  },

  // Leadership (10 questions)
  {
    id: "lead-1",
    category: "leadership",
    categoryLabel: "Engineering Leadership",
    difficulty: "Staff Level",
    title: "Cross-Functional Engineering Roadmapping",
    question: "How do you balance tech debt remediation with aggressive product feature delivery when negotiating with Product and Business leaders?",
    hints: ["Quantify tech debt in terms of revenue risk and velocity drag", "Allocate dedicated 20% capacity budget for platform health", "Tie refactors to upcoming product capabilities"],
    evaluationRubric: {
      situation: "Monolith technical debt slowing feature velocity by 40%.",
      task: "Secure executive sign-off for a 2-quarter platform modernization initiative.",
      action: "Presented data linking legacy build times and incident frequency to direct sprint revenue loss.",
      result: "Secured dedicated 20% platform sprint allocation; improved release velocity by 55%.",
    },
    candidateSnippet: "I translated technical debt into business language—demonstrating that our 45-minute CI build cycle was costing 180 engineering hours monthly. By pairing refactors directly with product roadmap goals, we gained VP alignment...",
    starBreakdown: { situation: 95, task: 97, action: 96, result: 96 },
    pacing: "140 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 96,
  },

  // Backend & Distributed (10 questions)
  {
    id: "be-1",
    category: "backend",
    categoryLabel: "Backend & Systems",
    difficulty: "Hard",
    title: "Database Deadlock Prevention & Isolation Levels",
    question: "Explain how you troubleshoot and eliminate database deadlocks under high-concurrency write workloads in PostgreSQL.",
    hints: ["Consistent lock ordering across transactions", "Optimistic concurrency control with version column", "Choosing appropriate transaction isolation (Read Committed vs Serializable)"],
    evaluationRubric: {
      situation: "Flash sale checkout causing PostgreSQL deadlock errors on inventory row locks.",
      task: "Eliminate deadlocks while maintaining strict stock integrity.",
      action: "Standardized alphabetical item lock acquisition order and introduced Redis distributed lock leasing.",
      result: "Reduced checkout lock contention from 8.5% to 0.001% at 15k concurrent buyers.",
    },
    candidateSnippet: "We identified that concurrent transactions were acquiring row locks in non-deterministic order. I enforced sorting row locks by primary key prior to batch updates and implemented optimistic locking with version counters...",
    starBreakdown: { situation: 94, task: 95, action: 97, result: 95 },
    pacing: "141 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 95,
  },

  // Product Engineering (10 questions)
  {
    id: "prod-1",
    category: "product",
    categoryLabel: "Product & Execution",
    difficulty: "Medium",
    title: "A/B Testing Statistical Significance & Telemetry",
    question: "How do you architect a client-side feature flagging and A/B experimentation system that prevents visual flicker (FOOC)?",
    hints: ["Edge cookie evaluation before HTML generation", "Zero-latency in-memory flag cache", "Telemetry tracking of exposure events"],
    evaluationRubric: {
      situation: "A/B test causing 200ms layout flicker, distorting user conversion metrics.",
      task: "Deliver instant variation rendering without client-side DOM swapping.",
      action: "Executed flag evaluation at Vercel Edge Middleware to stream the variant directly in initial HTML.",
      result: "Eliminated 100% of variant flash; valid statistical significance reached in 8 days.",
    },
    candidateSnippet: "We moved experimentation assignment from client-side useEffect execution to Edge Middleware, evaluating user cookie buckets prior to SSR and streaming the exact DOM variant with zero layout shift...",
    starBreakdown: { situation: 93, task: 94, action: 96, result: 94 },
    pacing: "142 WPM (Optimal)",
    fillerWords: "0 detected",
    score: 94,
  },
];

export const COPILOT_KNOWLEDGE_BASE: CopilotKnowledgeItem[] = [
  {
    id: "kb-ats-audit",
    category: "ATS",
    triggers: ["ats", "keyword", "parse", "scan", "greenhouse", "workday", "lever"],
    title: "Deterministic ATS Lexical Diagnostic",
    responseMarkdown: `### 📄 Deterministic ATS Parser Analysis

**ATS Compatibility**: 94/100 (Workday, Greenhouse & Lever AST Compliant)

**Key Diagnostic Findings**:
1. **Quantified Experience Ratio**: 92% of experience bullets feature measurable metrics.
2. **Missing High-Signal Keywords**: \`CRDTs\`, \`OpenTelemetry\`, \`Server Actions\`, \`Core Web Vitals\`.
3. **AST Structure**: Single-column layout parsed with 100% hierarchy accuracy across text nodes.

**Recommended Immediate Bullet Polish**:
- *Before*: "Built frontend components and improved page loading time."
- *After*: "Architected Next.js 15 streaming SSR pipeline, reducing LCP by 420ms and cutting bundle size by 34% across 2.1M monthly sessions."`,
    tags: ["ATS Match: 94%", "4 Keywords Found", "Diff Generated"],
    metrics: { label: "Impact Score", value: "+24 pts" },
  },
  {
    id: "kb-interview-star",
    category: "Interview",
    triggers: ["interview", "star", "behavioral", "amazon", "conflict", "mock", "practice"],
    title: "AI Voice Mock Interview: STAR Framework Evaluation",
    responseMarkdown: `### 🎙️ AI Technical Mock Simulation

**Interviewer Prompt**:
> *"Describe a high-severity production regression caused by state synchronization across distributed clients, and how you resolved it under pressure."*

**STAR Evaluation Breakdown**:
- **Situation (95%)**: Concise context detailing customer impact and telemetry trigger alerts.
- **Task (92%)**: Explicit definition of rollback SLAs and root-cause ownership.
- **Action (96%)**: Applied CRDT optimistic rollback and isolated reproduction tests.
- **Result (90%)**: Zero data loss, restored sub-100ms sync within 14 minutes.

**Next Drill**: Try the *"Micro-Frontend State Isolation"* question in the Voice Studio.`,
    tags: ["STAR Score: 95/100", "0 Filler Words", "Pacing: 140 WPM"],
    metrics: { label: "Readiness Index", value: "96/100" },
  },
  {
    id: "kb-roadmap-staff",
    category: "Roadmap",
    triggers: ["roadmap", "study", "plan", "staff", "curriculum", "learn", "milestone"],
    title: "Personalized 6-Week Staff Frontend Roadmap",
    responseMarkdown: `### 🗺️ Tailored 6-Week Staff Frontend Mastery Roadmap

- **Week 1–2**: React 19 Compiler, Server Actions & Streaming Hydration internals.
- **Week 3–4**: Distributed State Machines, CRDTs & Edge Offline Sync (Yjs + WebSockets).
- **Week 5**: High-Concurrency Architecture, Edge Rate Limiting & Telemetry (OpenTelemetry).
- **Week 6**: Executive RFC authoring, cross-functional consensus & system design mock trials.

**Estimated Velocity**: 3.2x faster than unstructured preparation.`,
    tags: ["4 Milestones", "3 Target Projects", "Verified Curriculum"],
    metrics: { label: "Estimated Velocity", value: "3.2x Faster" },
  },
  {
    id: "kb-salary-band",
    category: "Salary",
    triggers: ["salary", "compensation", "band", "negotiate", "offer", "equity", "levels"],
    title: "Staff & Senior Tech Compensation Benchmarks (2025/2026)",
    responseMarkdown: `### 💰 Real-Time Verified Salary & Equity Bands

**Staff Frontend / Platform Roles (Tier 1 US Tech)**:
- **Base Salary**: $220,000 – $275,000
- **Annual Equity (RSU/Options)**: $150,000 – $250,000 / yr
- **Target Total Comp (TC)**: $370,000 – $525,000

**Key Negotiation Levers**:
1. Multiple competing offers at final round stage (+15–25% equity increase).
2. Demonstrating cross-org scope impact on revenue-critical services.
3. Requesting accelerated vesting schedules or sign-on bonuses.`,
    tags: ["Verified Data", "Tier 1 US Tech", "Levels.fyi Aligned"],
    metrics: { label: "Median TC", value: "$425,000" },
  },
  {
    id: "kb-system-design",
    category: "System Design",
    triggers: ["system design", "distributed", "caching", "architecture", "crdt", "kafka", "redis"],
    title: "System Design Framework for Staff Roles",
    responseMarkdown: `### 🏗️ 4-Step System Design Blueprint

1. **Scope & SLA Requirements (5 mins)**: Clarify QPS (e.g. 50k reads/sec, 5k writes/sec), latency bounds (<50ms p99), and consistency model (eventual vs strong).
2. **High-Level Diagram (10 mins)**: Client ➔ CDN/Edge ➔ API Gateway ➔ App Service ➔ DB + Cache Cluster.
3. **Deep Dive Bottlenecks (20 mins)**: Address cache invalidation, thundering herds, partition recovery, and horizontal autoscaling.
4. **Resiliency & Telemetry (10 mins)**: Circuit breakers, rate limiters, dead-letter queues, and OpenTelemetry spans.`,
    tags: ["System Design", "Staff Architecture", "RFC Ready"],
    metrics: { label: "Blueprint Grade", value: "A+" },
  },
];
